[Application]
	Name = "courses"
	Version = "1.0.0"

[Server]
	Scheme = "http://"
	Ip = "from env"
	Host = "from env"
	Port = "from env"

[DB]
	User = "from env"
	Password = "from env"
	Name = "from env"
	Driver = "postgres"
	Host = "from env"
	Port = ":5432"
	ModeString = "?sslmode=disable"

[Session]
	Key = "from env"

[Email]
	From = "from env"
	Password = "from env"
	Host = "mail.netangels.ru"
	Port = ":465"

[YookassaProvider]
	Host = "https://api.yookassa.ru/v3"
	[YookassaProvider.Endpoint.CreatePayment]
		Path = "/payments"
		Method = "POST"
	[YookassaProvider.Endpoint.GetPayment]
		Path = "/payments"
		Method = "GET"

[YookassaAuth]
	Login = "from env"
	Password = "from env"