[Application]
	Name = "courses"
	Version = "0.0.1"

[Server]
	Scheme = "http://"
	Host = "localhost"
	Port = ":80"

[DB]
	User = "from env"
	Password = "from env"
	Name = "from env"
	Driver = "postgres"
	Host = "localhost"
	Port = "5432"

[Session]
	Key = "from env"

[Email]
	From = "from env"
	Password = "from env"
	Host = "smtp.yandex.ru"
	Port = ":587"

[YookassaProvider]
	Host = "https://api.yookassa.ru/v3"
	[YookassaProvider.Endpoint.CreatePayment]
		Path = "/payments"
		Method = "POST"
	[YookassaProvider.Endpoint.GetPayment]
		Path = "/payments"
		Method = "GET"

[YookassaAuth]
	Login = "from env"
	Password = "from env"